package scu.dn.used_cars_backend.common.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {

	UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
	FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
	INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
	USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_NOT_FOUND"),
	ACCOUNT_SUSPENDED(HttpStatus.FORBIDDEN, "ACCOUNT_SUSPENDED"),
	VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "VALIDATION_FAILED"),
	INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_SERVER_ERROR"),

	VEHICLE_NOT_FOUND(HttpStatus.NOT_FOUND, "VEHICLE_NOT_FOUND"),
	BRAND_NOT_FOUND(HttpStatus.NOT_FOUND, "BRAND_NOT_FOUND"),
	MODEL_NOT_FOUND(HttpStatus.NOT_FOUND, "MODEL_NOT_FOUND"),
	BRANCH_NOT_FOUND(HttpStatus.NOT_FOUND, "BRANCH_NOT_FOUND"),
	INVALID_PRICE(HttpStatus.BAD_REQUEST, "INVALID_PRICE"),
	INVALID_YEAR(HttpStatus.BAD_REQUEST, "INVALID_YEAR"),
	LISTING_ID_CONFLICT(HttpStatus.CONFLICT, "LISTING_ID_CONFLICT"),
	VEHICLE_ALREADY_SAVED(HttpStatus.CONFLICT, "VEHICLE_ALREADY_SAVED"),
	VEHICLE_NOT_SAVED(HttpStatus.NOT_FOUND, "VEHICLE_NOT_SAVED"),

	// Tier 3.2 — Booking & test drive
	BOOKING_NOT_FOUND(HttpStatus.NOT_FOUND, "BOOKING_NOT_FOUND"),
	SLOT_NOT_FOUND(HttpStatus.BAD_REQUEST, "SLOT_NOT_FOUND"),
	SLOT_FULLY_BOOKED(HttpStatus.BAD_REQUEST, "SLOT_FULLY_BOOKED"),
	VEHICLE_NOT_AVAILABLE(HttpStatus.BAD_REQUEST, "VEHICLE_NOT_AVAILABLE"),
	BOOKING_CANNOT_CANCEL(HttpStatus.BAD_REQUEST, "BOOKING_CANNOT_CANCEL"),
	INVALID_STATUS_TRANSITION(HttpStatus.BAD_REQUEST, "INVALID_STATUS_TRANSITION"),
	BOOKING_ACCESS_DENIED(HttpStatus.FORBIDDEN, "BOOKING_ACCESS_DENIED");

	private final HttpStatus httpStatus;
	private final String code;

	ErrorCode(HttpStatus httpStatus, String code) {
		this.httpStatus = httpStatus;
		this.code = code;
	}
}
