package scu.dn.used_cars_backend.common.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {

	UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
	/** Quá nhiều request đăng nhập/đăng ký từ cùng IP (rate limit). */
	RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "RATE_LIMITED"),
	FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
	INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
	INVALID_CURRENT_PASSWORD(HttpStatus.BAD_REQUEST, "INVALID_CURRENT_PASSWORD"),
	PASSWORD_TOO_SHORT(HttpStatus.BAD_REQUEST, "PASSWORD_TOO_SHORT"),
	USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_NOT_FOUND"),
	ACCOUNT_SUSPENDED(HttpStatus.FORBIDDEN, "ACCOUNT_SUSPENDED"),
	/** JWT hợp lệ nhưng user phải hoàn tất đặt mật khẩu mới (sau reset admin). */
	PASSWORD_CHANGE_REQUIRED(HttpStatus.FORBIDDEN, "PASSWORD_CHANGE_REQUIRED"),
	VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "VALIDATION_FAILED"),
	INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_SERVER_ERROR"),

	VEHICLE_NOT_FOUND(HttpStatus.NOT_FOUND, "VEHICLE_NOT_FOUND"),
	BRAND_NOT_FOUND(HttpStatus.NOT_FOUND, "BRAND_NOT_FOUND"),
	MODEL_NOT_FOUND(HttpStatus.NOT_FOUND, "MODEL_NOT_FOUND"),
	BRANCH_NOT_FOUND(HttpStatus.NOT_FOUND, "BRANCH_NOT_FOUND"),
	INVALID_PRICE(HttpStatus.BAD_REQUEST, "INVALID_PRICE"),
	INVALID_YEAR(HttpStatus.BAD_REQUEST, "INVALID_YEAR"),
	LISTING_ID_CONFLICT(HttpStatus.CONFLICT, "LISTING_ID_CONFLICT"),
	VEHICLE_ALREADY_SAVED(HttpStatus.BAD_REQUEST, "VEHICLE_ALREADY_SAVED"),
	VEHICLE_NOT_SAVED(HttpStatus.NOT_FOUND, "VEHICLE_NOT_SAVED"),

	// Tier 3.2 — Booking & test drive
	BOOKING_NOT_FOUND(HttpStatus.NOT_FOUND, "BOOKING_NOT_FOUND"),
	SLOT_NOT_FOUND(HttpStatus.BAD_REQUEST, "SLOT_NOT_FOUND"),
	SLOT_FULLY_BOOKED(HttpStatus.BAD_REQUEST, "SLOT_FULLY_BOOKED"),
	VEHICLE_SLOT_TAKEN(HttpStatus.BAD_REQUEST, "VEHICLE_SLOT_TAKEN"),
	VEHICLE_NOT_AVAILABLE(HttpStatus.BAD_REQUEST, "VEHICLE_NOT_AVAILABLE"),
	BOOKING_CANNOT_CANCEL(HttpStatus.BAD_REQUEST, "BOOKING_CANNOT_CANCEL"),
	INVALID_STATUS_TRANSITION(HttpStatus.BAD_REQUEST, "INVALID_STATUS_TRANSITION"),
	BOOKING_ACCESS_DENIED(HttpStatus.FORBIDDEN, "BOOKING_ACCESS_DENIED"),

	// Tier 3.3 — Vehicle transfers
	TRANSFER_NOT_FOUND(HttpStatus.NOT_FOUND, "TRANSFER_NOT_FOUND"),
	VEHICLE_NOT_IN_BRANCH(HttpStatus.BAD_REQUEST, "VEHICLE_NOT_IN_BRANCH"),
	TRANSFER_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, "TRANSFER_ALREADY_EXISTS"),
	INVALID_TRANSFER_STATUS(HttpStatus.BAD_REQUEST, "INVALID_TRANSFER_STATUS"),
	TRANSFER_ACCESS_DENIED(HttpStatus.FORBIDDEN, "TRANSFER_ACCESS_DENIED"),
	USED_CAR_PURCHASE_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "USED_CAR_PURCHASE_REQUEST_NOT_FOUND"),
	USED_CAR_PURCHASE_REQUEST_ACCESS_DENIED(HttpStatus.FORBIDDEN, "USED_CAR_PURCHASE_REQUEST_ACCESS_DENIED"),
	USED_CAR_PURCHASE_REQUEST_INVALID_STATUS(HttpStatus.BAD_REQUEST, "USED_CAR_PURCHASE_REQUEST_INVALID_STATUS"),

	// Manager staff (Phase 2)
	STAFF_NOT_FOUND(HttpStatus.NOT_FOUND, "STAFF_NOT_FOUND"),
	STAFF_EMAIL_EXISTS(HttpStatus.CONFLICT, "STAFF_EMAIL_EXISTS"),
	STAFF_PHONE_EXISTS(HttpStatus.CONFLICT, "STAFF_PHONE_EXISTS"),
	STAFF_NOT_IN_BRANCH(HttpStatus.FORBIDDEN, "STAFF_NOT_IN_BRANCH"),
	STAFF_PEER_EDIT_FORBIDDEN(HttpStatus.FORBIDDEN, "STAFF_PEER_EDIT_FORBIDDEN"),

	/** Upload ảnh qua Cloudinary chưa cấu hình trên máy chủ */
	MEDIA_UPLOAD_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE, "MEDIA_UPLOAD_NOT_CONFIGURED"),
	/** URL Cloudinary không khớp cloud/folder/public_id đã cấp phép */
	CLOUDINARY_URL_INVALID(HttpStatus.BAD_REQUEST, "CLOUDINARY_URL_INVALID"),

	// Sprint 4 — Vehicle extras
	/** Ảnh xe không tìm thấy hoặc không thuộc xe này */
	IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "IMAGE_NOT_FOUND"),
	/** Trạng thái xe không hợp lệ (không nằm trong danh sách cho phép) */
	INVALID_VEHICLE_STATUS(HttpStatus.BAD_REQUEST, "INVALID_VEHICLE_STATUS"),
	/** Danh sách xe rỗng hoặc không hợp lệ */
	INVALID_VEHICLE_LIST(HttpStatus.BAD_REQUEST, "INVALID_VEHICLE_LIST"),
	/** Bản ghi bảo dưỡng không tìm thấy */
	MAINTENANCE_NOT_FOUND(HttpStatus.NOT_FOUND, "MAINTENANCE_NOT_FOUND"),

	// Sprint 5 — Admin users / roles
	USER_EMAIL_EXISTS(HttpStatus.CONFLICT, "USER_EMAIL_EXISTS"),
	ROLE_NOT_FOUND(HttpStatus.NOT_FOUND, "ROLE_NOT_FOUND"),
	ROLE_IN_USE(HttpStatus.CONFLICT, "ROLE_IN_USE"),

	RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "RESOURCE_NOT_FOUND"),

	ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "ORDER_NOT_FOUND"),
	DEPOSIT_NOT_FOUND(HttpStatus.NOT_FOUND, "DEPOSIT_NOT_FOUND"),
	VEHICLE_ALREADY_DEPOSITED(HttpStatus.BAD_REQUEST, "VEHICLE_ALREADY_DEPOSITED"),
	DEPOSIT_CANNOT_CANCEL(HttpStatus.BAD_REQUEST, "DEPOSIT_CANNOT_CANCEL"),
	DEPOSIT_CANNOT_CONFIRM(HttpStatus.BAD_REQUEST, "DEPOSIT_CANNOT_CONFIRM"),
	DEPOSIT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "DEPOSIT_ACCESS_DENIED"),
	ORDER_INVALID_STATUS_TRANSITION(HttpStatus.BAD_REQUEST, "ORDER_INVALID_STATUS_TRANSITION"),
	ORDER_CANNOT_CANCEL(HttpStatus.BAD_REQUEST, "ORDER_CANNOT_CANCEL"),
	ORDER_ACCESS_DENIED(HttpStatus.FORBIDDEN, "ORDER_ACCESS_DENIED"),
	// Chong that thoat: 1 xe chi 1 order active tai 1 thoi diem
	VEHICLE_HAS_ACTIVE_ORDER(HttpStatus.CONFLICT, "VEHICLE_HAS_ACTIVE_ORDER"),
	// Xe dang Reserved boi khach khac -> khong duoc tao don cho khach nay
	DEPOSIT_OWNER_MISMATCH(HttpStatus.CONFLICT, "DEPOSIT_OWNER_MISMATCH"),
	// Xe co coc active -> bat buoc phai di kem depositId trong request
	DEPOSIT_REQUIRED(HttpStatus.BAD_REQUEST, "DEPOSIT_REQUIRED"),
	// Coc da duoc dung cho don khac
	DEPOSIT_ALREADY_CONVERTED(HttpStatus.CONFLICT, "DEPOSIT_ALREADY_CONVERTED"),
	// Chuyen trang thai xe khong hop le theo state machine
	INVALID_VEHICLE_STATE_TRANSITION(HttpStatus.BAD_REQUEST, "INVALID_VEHICLE_STATE_TRANSITION"),
	PAYMENT_EXCEEDS_REMAINING(HttpStatus.BAD_REQUEST, "PAYMENT_EXCEEDS_REMAINING"),
	PAYMENT_FORBIDDEN(HttpStatus.FORBIDDEN, "PAYMENT_FORBIDDEN"),
	PAYMENT_AMOUNT_MISMATCH(HttpStatus.BAD_REQUEST, "PAYMENT_AMOUNT_MISMATCH"),

	NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "NOTIFICATION_NOT_FOUND"),
	ANNOUNCEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "ANNOUNCEMENT_NOT_FOUND"),
	MAIL_NOT_CONFIGURED(HttpStatus.UNPROCESSABLE_ENTITY, "MAIL_NOT_CONFIGURED"),

	INVALID_RESET_TOKEN(HttpStatus.BAD_REQUEST, "INVALID_RESET_TOKEN"),

	/** Google ID Token không hợp lệ, hết hạn, hoặc server chưa cấu hình Google Client ID */
	GOOGLE_AUTH_FAILED(HttpStatus.UNAUTHORIZED, "GOOGLE_AUTH_FAILED"),

	// Blog / Articles
	ARTICLE_NOT_FOUND(HttpStatus.NOT_FOUND, "ARTICLE_NOT_FOUND"),
	ARTICLE_CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "ARTICLE_CATEGORY_NOT_FOUND"),
	ARTICLE_SLUG_CONFLICT(HttpStatus.CONFLICT, "ARTICLE_SLUG_CONFLICT"),
	CATEGORY_SLUG_CONFLICT(HttpStatus.CONFLICT, "CATEGORY_SLUG_CONFLICT"),
	CATEGORY_IN_USE(HttpStatus.CONFLICT, "CATEGORY_IN_USE"),

	// Vehicle Reviews
	REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "REVIEW_NOT_FOUND"),
	REVIEW_ALREADY_EXISTS(HttpStatus.CONFLICT, "REVIEW_ALREADY_EXISTS"),
	REVIEW_NOT_ELIGIBLE(HttpStatus.BAD_REQUEST, "REVIEW_NOT_ELIGIBLE"),
	REVIEW_ACCESS_DENIED(HttpStatus.FORBIDDEN, "REVIEW_ACCESS_DENIED"),

	CONTRACT_NOT_FOUND(HttpStatus.NOT_FOUND, "CONTRACT_NOT_FOUND"),
	CONTRACT_ALREADY_SIGNED(HttpStatus.CONFLICT, "CONTRACT_ALREADY_SIGNED"),
	CONTRACT_EXPIRED(HttpStatus.BAD_REQUEST, "CONTRACT_EXPIRED"),
	DOCUMENT_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "DOCUMENT_SESSION_NOT_FOUND"),
	DOCUMENT_SESSION_EXPIRED(HttpStatus.BAD_REQUEST, "DOCUMENT_SESSION_EXPIRED"),
	DOCUMENT_SESSION_INVALID_TOKEN(HttpStatus.FORBIDDEN, "DOCUMENT_SESSION_INVALID_TOKEN"),

	CONSULTATION_NOT_FOUND(HttpStatus.NOT_FOUND, "CONSULTATION_NOT_FOUND"),
	CONSULTATION_ACCESS_DENIED(HttpStatus.FORBIDDEN, "CONSULTATION_ACCESS_DENIED"),

	CHAT_NOT_FOUND(HttpStatus.NOT_FOUND, "CHAT_NOT_FOUND"),
	CHAT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "CHAT_ACCESS_DENIED"),

	/** Tìm thấy nhiều user khớp email/phone — staff cần kiểm tra với admin. */
	CUSTOMER_IDENTITY_AMBIGUOUS(HttpStatus.CONFLICT, "CUSTOMER_IDENTITY_AMBIGUOUS"),

	BANK_CONNECTION_ERROR(HttpStatus.SERVICE_UNAVAILABLE, "BANK_CONNECTION_ERROR"),
	BANK_API_ERROR(HttpStatus.BAD_GATEWAY, "BANK_API_ERROR"),

	// SMS OTP Verification
	OTP_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "OTP_GENERATION_FAILED"),
	OTP_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, "OTP_ALREADY_EXISTS"),
	OTP_INVALID_FORMAT(HttpStatus.BAD_REQUEST, "OTP_INVALID_FORMAT"),
	OTP_INVALID_CODE(HttpStatus.BAD_REQUEST, "OTP_INVALID_CODE"),
	OTP_EXPIRED(HttpStatus.BAD_REQUEST, "OTP_EXPIRED"),
	OTP_EXHAUSTED(HttpStatus.BAD_REQUEST, "OTP_EXHAUSTED"),
	OTP_ALREADY_VERIFIED(HttpStatus.BAD_REQUEST, "OTP_ALREADY_VERIFIED"),
	OTP_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "OTP_RATE_LIMITED"),
	OTP_REFERENCE_INVALID(HttpStatus.BAD_REQUEST, "OTP_REFERENCE_INVALID"),
	SMS_VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "SMS_VALIDATION_FAILED"),
	SMS_DUPLICATE(HttpStatus.BAD_REQUEST, "SMS_DUPLICATE"),
	OTP_RESEND_TOO_FAST(HttpStatus.BAD_REQUEST, "OTP_RESEND_TOO_FAST"),
	OTP_RESEND_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "OTP_RESEND_LIMIT_EXCEEDED"),
	DEVICE_KEY_MISSING(HttpStatus.UNAUTHORIZED, "DEVICE_KEY_MISSING"),
	DEVICE_KEY_INVALID(HttpStatus.FORBIDDEN, "DEVICE_KEY_INVALID"),
	IP_BLOCKED(HttpStatus.TOO_MANY_REQUESTS, "IP_BLOCKED");

	private final HttpStatus httpStatus;
	private final String code;

	ErrorCode(HttpStatus httpStatus, String code) {
		this.httpStatus = httpStatus;
		this.code = code;
	}
}
