
name: Deploy Backend

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy backend

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.SSH_KEY }}

          port: ${{ secrets.PORT }}

          script: |

            cd /var/www/used-cars-backend

            git reset --hard

            git pull origin main

            ./mvnw clean package -DskipTests

            pkill -f "used-cars-backend" || true

            nohup java -jar target/*.jar > /var/log/used-cars-backend.log 2>&1 &

