
name: Deploy Backend

on:

  push:

    branches: [main]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.SSH_KEY }}

          port: ${{ secrets.PORT }}

          command_timeout: 20m

          script: |

            cd /opt/backend/app && git reset --hard && git pull origin main && chmod +x mvnw && ./mvnw clean package -Dmaven.test.skip=true && systemctl restart used-cars-backend

